### ISSUE TITLE
Benchmarking support

### ISSUE THREAD

**Issue by PaulBone** [mayhemer/logan#26]
Hi, I'm using this tool as a benchmark for JavaScript performance. To make things easier could you add calls to performance.mark() and performance.measure() https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API at the approprite places so that we can measure how long it takes to load and process files?

I attempted this myself but could not obviously find the right places.  I placed the calls in consumeFiles() but did not get the right places, I think because this is asynchronous and I don't see where loading finishes.

Could you do that for https://janbambas.cz/moz/bug1391710/ also? Maybe maintain it as a seperate branch.

Thanks.

**Comment by mayhemer** [comment]
https://github.com/mayhemer/logan/commit/08e5b4473e730cb03e4734bf1663503ca51f18fe

I've also add that to the test installation manually.

**Comment by mayhemer** [comment]
I don't know how exactly performance markers and measurements work, but I've also added a measurement at https://github.com/mayhemer/logan/commit/3a529bb0abcf1768d154836d124593600abe4e66

**Comment by PaulBone** [comment]
As far as I'm aware - and I'm not actually a JS developer - They can do logging and/or add events to profiling tools. For example I'm using http://perf-html.io to benchmark Firefox while writting your tool, and I'll be able to measure things like how long it takes to load the logs as I modify Firefox.

**Comment by mayhemer** [comment]
@PaulBone, I've added the following:

      performance.mark("parsing-start");
      
      /* the whole log file set parsing processing code, async */
      
      performance.mark("parsing-end");
      performance.measure("parsing", "parsing-start", "parsing-end");

Let me know, if this is what you want.

**Comment by PaulBone** [comment]
Yes, that's exactly what I meant. (sorry for the delay, looks like I've had this browser tab open all this time).
