### ISSUE TITLE
Add ability to link to the current view of the log

### ISSUE THREAD

**Issue by valenting** [mayhemer/logan#28]
I would love to have the ability to share my findings with others via a link, similar to the Gecko Profiler.
Logan doesn't currently host profiles, so it would need to have the ability to load profiles from a file on the internet, and I guess all of the filters would be provided by query params.

**Comment by mayhemer** [comment]
This is partially done by https://github.com/mayhemer/logan/commit/b7ace2068171a71e0e76e54283c019b0286420a6 and https://github.com/mayhemer/logan/commit/dfc61b243924fc7bacc94f2a3eaa39face6b5370

Sharing a log via web is still a bit tricky, there is no support for zipped files and URL must be served with allow-origin response headers.
