### ISSUE TITLE
Add support for Http2PushedStreams

### ISSUE THREAD

**Issue by nwgh** [mayhemer/logan#30]
This one may be a bit tricky (or may not), because due to inheritance, some (many?) log lines from Http2PushedStreams show up as Http2Stream. It would be really useful to have, though. Probably also want to add Http2PushTransactionBuffer at the same time.

**Comment by mayhemer** [comment]
Definitely!  Does this anything more than just proper ctor/dtor and linking (to a concrete class) logging?  If not, I will need to understand the structure and linking first.  If you can describe it here or somehow in person, it would greatly help.

**Comment by nwgh** [comment]
The push stream ctor logs at https://searchfox.org/mozilla-central/rev/6d1ab84b4b39fbfb9505d4399857239bc15202ef/netwerk/protocol/http/Http2Push.cpp#78 - it gives you the this pointer, and the stream id. I believe the regular Http2Stream ctor code will run (and therefore log) before that line is hit, so that will need to be taken into account.

Later on, once gecko generates a transaction to use whatever was pushed to us, the code at https://searchfox.org/mozilla-central/rev/6d1ab84b4b39fbfb9505d4399857239bc15202ef/netwerk/protocol/http/Http2Stream.cpp#500 will run, which has the pointer of the pushed stream logged. That line already shows up in logs as matched with an Http2Stream (I believe), so I think you already have the info to match the two there. Matching those two allows us to chain from the pushed stream to the consumer stream to the consumer transaction. (Doesn't need to be in logan explicitly, as long as I can click through like I do for session -> stream -> transaction.)

Let me know if you need anything else from me.

**Comment by mayhemer** [comment]
And how are the objects related in reality?  I still don't follow what to link with what - a pushed stream with a regular stream?  I think that is the last bit I need to update logan rules, hopefully.

**Comment by mayhemer** [comment]
Aha, Http2PushedStream derives from Http2Stream.  Still, not sure what exactly you want me to do.

**Comment by mayhemer** [comment]
And if you can, please give me a log to test with or a link to a test case/web I can produce a log to test with, thanks.

**Comment by mayhemer** [comment]
Thanks!  This is an awesome description.

Deps on https://bugzilla.mozilla.org/show_bug.cgi?id=1495180

**Comment by mayhemer** [comment]
If the only stream actually used in the log was the one you refer, then this is fixed with https://github.com/mayhemer/logan/commit/57bda9007348b12219debc86b2c0c34b45a66006
